spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
#        stream-in:
#          destination: stream
#          contentType: application/json
        stream-out:
          destination: stream
          contentType: application/json