spring:
  cloud:
    stream:
      bindings:
        output:
          destination: email-topic
          contentType: application/json
        input:
          destination: success-topic
          group: finalizers